version: '3.8'

services:
  georgian_game:
    hostname: georgian_game
    container_name: georgian_game
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: unless-stopped