version: '3.8'

services:
  georgianGame:
    hostname: georgianGame
    container_name: georgianGame
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: unless-stopped